import type { WorldPreset } from './types';

export const farm: WorldPreset = {
  id: 'farm',
  name: 'Farm',
  thumbnail: '/worlds/farm.jpg',
  sky: {
    top: '#84b9d5',
    horizon: '#f2eee1',
    fogColor: '#ead7b5',
    fogNear: 75,
    fogFar: 235,
    sunColor: '#ffe7b3',
    sunIntensity: 2.1,
    hemiSky: '#ddeaff',
    hemiGround: '#ac8856',
    hemiIntensity: 1.3,
    hills: { colors: ['#c5aa69', '#a9a168', '#d3b577'], height: [10, 26], width: [34, 60] },
  },
  terrain: {
    base: '#b3a064',
    speckles: ['#a28f55', '#c8ad73', '#958856'],
    patches: ['#c4ac75', '#a69d61', '#d4bc83'],
    bands: [
      { side: 'right', from: 10, to: 26, color: '#d4ac57', y: 0.03 },
      { side: 'right', from: 26, to: 40, color: '#a47a56', y: 0.03 },
      { side: 'right', from: 40, to: 62, color: '#d6b771', y: 0.03 },
      { side: 'left', from: 10, to: 30, color: '#aaa569', y: 0.03 },
      { side: 'left', from: 30, to: 52, color: '#b58c5c', y: 0.03 },
    ],
  },
  road: {
    // Country dirt road: no painted lines.
    asphalt: '#99765b',
    asphaltSpeckle: '#b68f69',
    edgeLine: null,
    centerLine: null,
    shoulder: '#bf985f',
    curve: [
      { amplitude: 14, wavelength: 520, phase: 1.1 },
      { amplitude: 6, wavelength: 190, phase: 0.4 },
    ],
  },
  props: {
    perChunk: [8, 12],
    shoulderCones: 4,
    shoulderProp: 'fence',
    shoulderDistance: 0.9,
    items: [
      { kind: 'barn', weight: 1.2, minDistance: 14, maxDistance: 26, scale: [1, 1.1], maxPerChunk: 1, facing: 'road' },
      { kind: 'silo', weight: 1, minDistance: 16, maxDistance: 30, scale: [0.9, 1.1], maxPerChunk: 1 },
      { kind: 'hayBale', weight: 2.5, minDistance: 4, maxDistance: 22, scale: [0.9, 1.2], maxPerChunk: 4 },
      { kind: 'cow', weight: 3, minDistance: 4, maxDistance: 20, scale: [0.9, 1.1], maxPerChunk: 3 },
      { kind: 'sheep', weight: 2, minDistance: 3, maxDistance: 16, scale: [0.9, 1.1], maxPerChunk: 3 },
      { kind: 'windmill', weight: 0.8, minDistance: 18, maxDistance: 34, scale: [1, 1.2], maxPerChunk: 1, facing: 'traffic' },
      { kind: 'tractor', weight: 1, minDistance: 5, maxDistance: 18, scale: [1, 1], maxPerChunk: 1 },
      { kind: 'autumnTree', weight: 5, minDistance: 4, maxDistance: 32, scale: [0.9, 1.4], maxPerChunk: 4 },
      { kind: 'pumpkinPile', weight: 3, minDistance: 2, maxDistance: 6, scale: [0.9, 1.2], maxPerChunk: 2 },
      { kind: 'leafPile', weight: 2, minDistance: 0.8, maxDistance: 4, scale: [0.8, 1.2], maxPerChunk: 2 },
      { kind: 'scarecrow', weight: 1, minDistance: 3, maxDistance: 9, scale: [0.95, 1.1], maxPerChunk: 1, facing: 'road' },
      { kind: 'cornRows', weight: 1.5, minDistance: 8, maxDistance: 23, scale: [0.9, 1.1], maxPerChunk: 1, facing: 'road' },
      { kind: 'pumpkinPatch', weight: 1, minDistance: 10, maxDistance: 12, scale: [1, 1], maxPerChunk: 1,
        side: 'right', facing: 'road', every: { chunks: 6, offset: 1 } },
      { kind: 'harvestStand', weight: 1, minDistance: 6, maxDistance: 7, scale: [1, 1], maxPerChunk: 1,
        side: 'left', facing: 'road', every: { chunks: 6, offset: 4 } },
      { kind: 'harvestRide', weight: 1, minDistance: 16.5, maxDistance: 16.5, scale: [1, 1], maxPerChunk: 1,
        side: 'right', facing: 'traffic', every: { chunks: 6, offset: 3 } },
    ],
  },
  cropDuster: { altitude: 24, intervalSec: [28, 43] },
  traffic: { enabled: true, vehicles: ['tractor', 'pickup', 'car', 'van'] },
  audio: {
    engineBaseHz: 50,
    ambience: { noiseLevel: 0.035, noiseCutoff: 600, events: ['moo'], eventInterval: [9, 16] },
  },
};
